// <auto-generated />
using System;
using Demo02_WebAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo02_WebAPI.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220211152507_AddDataBook")]
    partial class AddDataBook
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsAuthorId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("BooksBookId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("AuthorsAuthorId", "BooksBookId");

                    b.HasIndex("BooksBookId");

                    b.ToTable("AuthorBook");

                    b.HasData(
                        new
                        {
                            AuthorsAuthorId = new Guid("4500f329-e046-4395-b532-fe734b9bd637"),
                            BooksBookId = new Guid("528b0102-c701-421a-84b6-b3bcb7973cd5")
                        });
                });

            modelBuilder.Entity("Demo02_WebAPI.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("author_id");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("lastname");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("4500f329-e046-4395-b532-fe734b9bd637"),
                            Firstname = "Riri",
                            Lastname = "Duck"
                        },
                        new
                        {
                            AuthorId = new Guid("8dc71cc2-bfaf-4792-bbc0-9a3fd6ad9e22"),
                            Firstname = "Della",
                            Lastname = "Duck"
                        },
                        new
                        {
                            AuthorId = new Guid("b3a11a9f-c717-4984-bd69-2f4e4f880b16"),
                            Firstname = "Zaza",
                            Lastname = "Vanderquack"
                        },
                        new
                        {
                            AuthorId = new Guid("08539e80-348d-4dd4-b64d-f31259f39353"),
                            Firstname = "Gontran",
                            Lastname = "Bonheur"
                        });
                });

            modelBuilder.Entity("Demo02_WebAPI.DAL.Entities.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("book_id");

                    b.Property<short?>("NbPage")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("nb_page");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("title");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = new Guid("528b0102-c701-421a-84b6-b3bcb7973cd5"),
                            NbPage = (short)42,
                            Title = "Hello World"
                        },
                        new
                        {
                            BookId = new Guid("4685f5aa-9b4d-4160-86f6-6b86ddd2f168"),
                            Title = "Bonjour"
                        });
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Demo02_WebAPI.DAL.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo02_WebAPI.DAL.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
