// <auto-generated />
using System;
using Demo02_WebAPI.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Demo02_WebAPI.DAL.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220210151447_AddDataAuthor")]
    partial class AddDataAuthor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.Property<Guid>("AuthorsAuthorId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.Property<Guid>("BooksBookId")
                        .HasColumnType("UNIQUEIDENTIFIER");

                    b.HasKey("AuthorsAuthorId", "BooksBookId");

                    b.HasIndex("BooksBookId");

                    b.ToTable("AuthorBook");
                });

            modelBuilder.Entity("Demo02_WebAPI.DAL.Entities.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("author_id");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("lastname");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = new Guid("6e2581bd-2227-4840-a116-db904ee67aa2"),
                            Firstname = "Riri",
                            Lastname = "Duck"
                        },
                        new
                        {
                            AuthorId = new Guid("a8392ee1-9582-4394-ba11-a085dd3b26cd"),
                            Firstname = "Della",
                            Lastname = "Duck"
                        },
                        new
                        {
                            AuthorId = new Guid("624f8d55-bd15-4c80-bf60-98da547afda7"),
                            Firstname = "Zaza",
                            Lastname = "Vanderquack"
                        },
                        new
                        {
                            AuthorId = new Guid("0ce198f0-95a3-4053-b08f-1481a91c5531"),
                            Firstname = "Gontran",
                            Lastname = "Bonheur"
                        });
                });

            modelBuilder.Entity("Demo02_WebAPI.DAL.Entities.Book", b =>
                {
                    b.Property<Guid>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UNIQUEIDENTIFIER")
                        .HasColumnName("book_id");

                    b.Property<short?>("NbPage")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("nb_page");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("NVARCHAR(250)")
                        .HasColumnName("title");

                    b.HasKey("BookId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("AuthorBook", b =>
                {
                    b.HasOne("Demo02_WebAPI.DAL.Entities.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demo02_WebAPI.DAL.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("BooksBookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
